import type { Metadata } from "next";
import { BRAND, SITE_URL } from "@/lib/brand";

/**
 * Metadata for a public page: canonical address plus matching Open Graph tags.
 * `title` is the page's own title; the root layout appends the brand to the
 * <title> tag, so do not include it here.
 */
export function pageMetadata({
  title,
  description,
  path,
}: {
  title: string;
  description: string;
  path: `/${string}`;
}): Metadata {
  const url = `${SITE_URL}${path}`;
  return {
    title,
    description,
    alternates: { canonical: url },
    openGraph: {
      type: "website",
      siteName: BRAND.name,
      locale: "en_GB",
      title,
      description,
      url,
      // Named here because a page that sets its own Open Graph block does not
      // pick up the image generated by src/app/opengraph-image.tsx.
      images: [
        {
          url: "/opengraph-image",
          width: 1200,
          height: 630,
          alt: `${BRAND.name}: ${BRAND.tagline}`,
        },
      ],
    },
  };
}
