import type { Metadata } from "next";
import { MarketingShell } from "@/components/marketing/marketing-shell";
import { GatedDownload } from "@/components/marketing/gated-download";
import { SITE_URL } from "@/lib/brand";

export const metadata: Metadata = {
  title: "Free call sheet template (UK) for video production",
  description:
    "A clean, professional call sheet template for UK video shoots: call times, schedule, locations with parking and nearest A&E, crew list, key contacts and safety notes. Free PDF download.",
  alternates: { canonical: `${SITE_URL}/templates/call-sheet-template` },
};

export default function CallSheetTemplatePage() {
  return (
    <MarketingShell source="template-call-sheet">
      <h1 className="mt-4 text-3xl font-bold tracking-tight">Free call sheet template</h1>
      <p className="mt-4 text-neutral-600">
        A call sheet is the one document every crew member actually reads. This template covers
        what a UK video shoot needs and nothing it does not: call times per person, the
        day&apos;s schedule, locations with parking notes and the nearest A&amp;E, key contacts,
        weather with sunrise and sunset, and a safety section your crew can acknowledge.
      </p>

      <div className="mt-8">
        <GatedDownload source="template-call-sheet" file="/downloads/call-sheet-template.pdf" />
      </div>

      <h2 className="mt-10 text-xl font-semibold tracking-tight">
        What a good call sheet includes
      </h2>
      <ul className="mt-3 list-disc space-y-2 pl-5 text-neutral-600">
        <li>
          <strong>General call and per-person call times.</strong> The single most-checked detail
          on the sheet. Put both, prominently.
        </li>
        <li>
          <strong>Location with practicalities.</strong> Full address, a maps link, where to park
          and how to get in. For UK shoots, add what3words and the nearest A&amp;E so nobody has
          to search for it in a bad moment.
        </li>
        <li>
          <strong>The schedule.</strong> Time blocks, not prose. Crew scan it; they do not read it.
        </li>
        <li>
          <strong>Crew list with phone numbers.</strong> Who is on set, what they do, how to reach
          them when they are late.
        </li>
        <li>
          <strong>Key contacts.</strong> Producer and first point of contact, names and numbers.
        </li>
        <li>
          <strong>Weather, sunrise and sunset.</strong> Decides lenses, layers and lunch timing.
        </li>
        <li>
          <strong>Safety notes.</strong> A short summary of the risk assessment, acknowledged by
          everyone before the day.
        </li>
      </ul>

      <h2 className="mt-10 text-xl font-semibold tracking-tight">
        Or skip the template entirely
      </h2>
      <p className="mt-3 text-neutral-600">
        This PDF was generated by Unit, where call sheets assemble themselves from your project:
        AI reads the client brief, the weather and sunrise fill in automatically, crew confirm on
        their phones and check in on the day. The waitlist form below gets you early access.
      </p>
    </MarketingShell>
  );
}
