/**
 * The rate card, taken line by line from the quote sheet this replaces.
 *
 * Every line of the sheet's TEMP BUDGET tab is here, in the sheet's own order
 * and under the sheet's own section headings — so a producer who knows the
 * spreadsheet finds the same list in the same shape, and nothing chargeable
 * is missing at the point somebody is pricing a job.
 *
 * Costs are internal and in pence. Client rates are not stored: they are
 * worked out from the cost and the quote's margins, which is what the sheet
 * did (see convex/lib/quoteMath.ts).
 *
 * A line quoted at cost — stock licensing, permits, couriers — carries a zero,
 * because the sheet leaves those to be typed per job rather than marked up.
 */

export type RateCardSeedItem = {
  category: "pre" | "production" | "art" | "equipment" | "travel" | "post";
  section: string;
  name: string;
  unit: "day" | "generic" | "track" | "mile" | "room" | "trip" | "minute" | "item";
  costPence: number;
  notes?: string;
};

export const RATE_CARD_SEED: RateCardSeedItem[] = [
  { category: "pre", section: "PRE - PRODUCTION", name: "Producer", unit: "day", costPence: 48628 },
  { category: "pre", section: "PRE - PRODUCTION", name: "Production Manager", unit: "day", costPence: 34912 },
  { category: "pre", section: "PRE - PRODUCTION", name: "Production Assistant", unit: "day", costPence: 24937 },
  { category: "pre", section: "PRE - PRODUCTION", name: "Director - Prep Day", unit: "day", costPence: 49875 },
  { category: "pre", section: "PRE - PRODUCTION", name: "Location Scout", unit: "day", costPence: 29925 },
  { category: "pre", section: "PRE - PRODUCTION", name: "Researcher", unit: "day", costPence: 24937 },
  { category: "pre", section: "PRE - PRODUCTION", name: "Storyboard Artist", unit: "day", costPence: 39900 },
  { category: "pre", section: "PRE - PRODUCTION", name: "Script writer", unit: "day", costPence: 49875 },
  { category: "pre", section: "PRE - PRODUCTION", name: "Permits & Permissons", unit: "generic", costPence: 0 },
  { category: "pre", section: "PRE - PRODUCTION", name: "Financial Administration", unit: "generic", costPence: 41560, notes: "Add to all quotes" },
  { category: "pre", section: "PRE - PRODUCTION", name: "Taxis/Couriers", unit: "generic", costPence: 0 },
  { category: "pre", section: "PRE - PRODUCTION", name: "Mileage", unit: "mile", costPence: 41 },
  { category: "pre", section: "PRE - PRODUCTION", name: "Accommodation", unit: "room", costPence: 16625 },
  { category: "pre", section: "PRE - PRODUCTION", name: "Per Diems", unit: "day", costPence: 2909 },
  { category: "pre", section: "PRE - PRODUCTION", name: "Fares", unit: "generic", costPence: 0, notes: "Travel Expenses" },
  { category: "pre", section: "PRE - PRODUCTION", name: "Other", unit: "generic", costPence: 0 },
  { category: "pre", section: "PRE - PRODUCTION - CASTING", name: "Casting Director", unit: "day", costPence: 49875, notes: "(inc. prep)" },
  { category: "pre", section: "PRE - PRODUCTION - CASTING", name: "Casting Director Recalls", unit: "day", costPence: 49875 },
  { category: "pre", section: "PRE - PRODUCTION - CASTING", name: "Video Edit of Casting", unit: "day", costPence: 49875 },
  { category: "pre", section: "PRE - PRODUCTION - CASTING", name: "Researcher", unit: "day", costPence: 24938 },
  { category: "pre", section: "PRE - PRODUCTION - CASTING", name: "Rehearsal room", unit: "generic", costPence: 0 },
  { category: "pre", section: "PRE - PRODUCTION - CASTING", name: "Taxis/Couriers", unit: "generic", costPence: 0 },
  { category: "pre", section: "PRE - PRODUCTION - CASTING", name: "Other", unit: "generic", costPence: 0 },
  { category: "production", section: "PRODUCTION CREW", name: "Director - Shoot", unit: "day", costPence: 54031 },
  { category: "production", section: "PRODUCTION CREW", name: "Producer - Shoot", unit: "day", costPence: 48628 },
  { category: "production", section: "PRODUCTION CREW", name: "Production Manager", unit: "day", costPence: 34912 },
  { category: "production", section: "PRODUCTION CREW", name: "Production Assistant", unit: "day", costPence: 24937 },
  { category: "production", section: "PRODUCTION CREW", name: "Runner", unit: "day", costPence: 20781 },
  { category: "production", section: "PRODUCTION CREW", name: "1st Assistant Director", unit: "day", costPence: 39900 },
  { category: "production", section: "PRODUCTION CREW", name: "Director of Photography", unit: "day", costPence: 45719 },
  { category: "production", section: "PRODUCTION CREW", name: "Camera Op", unit: "day", costPence: 39900 },
  { category: "production", section: "PRODUCTION CREW", name: "Studio Op", unit: "day", costPence: 39900 },
  { category: "production", section: "PRODUCTION CREW", name: "Camera Assistant", unit: "day", costPence: 34913 },
  { category: "production", section: "PRODUCTION CREW", name: "Focus Puller", unit: "day", costPence: 39900 },
  { category: "production", section: "PRODUCTION CREW", name: "Drone Op", unit: "day", costPence: 199501, notes: "(with kit) check licensing" },
  { category: "production", section: "PRODUCTION CREW", name: "Sound Op", unit: "day", costPence: 47797 },
  { category: "production", section: "PRODUCTION CREW", name: "Sound Op (with kit)", unit: "day", costPence: 64422 },
  { category: "production", section: "PRODUCTION CREW", name: "Gaffer", unit: "day", costPence: 54862 },
  { category: "production", section: "PRODUCTION CREW", name: "Spark", unit: "day", costPence: 37406 },
  { category: "production", section: "PRODUCTION CREW", name: "Autocue Operator", unit: "day", costPence: 49875, notes: "(with kit)" },
  { category: "production", section: "PRODUCTION CREW", name: "DIT", unit: "day", costPence: 69825 },
  { category: "production", section: "PRODUCTION CREW", name: "Data Wrangler", unit: "day", costPence: 34912, notes: "just laptop" },
  { category: "production", section: "PRODUCTION CREW", name: "Vision Mixer", unit: "day", costPence: 44887 },
  { category: "production", section: "PRODUCTION CREW", name: "VFX Supervisor", unit: "day", costPence: 79800 },
  { category: "production", section: "PRODUCTION CREW", name: "Photographer", unit: "day", costPence: 199501 },
  { category: "production", section: "PRODUCTION CREW", name: "Photographer Assistant", unit: "day", costPence: 34912 },
  { category: "production", section: "PRODUCTION CREW", name: "Travel Days", unit: "day", costPence: 29925 },
  { category: "production", section: "PRODUCTION CREW", name: "VO Artist", unit: "day", costPence: 99750, notes: "VO record fee per hour" },
  { category: "production", section: "PRODUCTION CREW", name: "VO Artist Usage Rights", unit: "generic", costPence: 49875 },
  { category: "production", section: "PRODUCTION CREW", name: "Director - Shoot (Overtime)", unit: "generic", costPence: 8105 },
  { category: "production", section: "PRODUCTION CREW", name: "Producer - Shoot (Overtime)", unit: "day", costPence: 7294 },
  { category: "production", section: "PRODUCTION CREW", name: "Production Manager (Overtime)", unit: "day", costPence: 5237 },
  { category: "production", section: "PRODUCTION CREW", name: "Production Assistant (Overtime)", unit: "day", costPence: 3741 },
  { category: "production", section: "PRODUCTION CREW", name: "Runner (Overtime)", unit: "day", costPence: 3117 },
  { category: "production", section: "PRODUCTION CREW", name: "1st Assistant Director (Overtime)", unit: "day", costPence: 5985 },
  { category: "production", section: "PRODUCTION CREW", name: "Director of Photography (Overtime)", unit: "day", costPence: 6858 },
  { category: "production", section: "PRODUCTION CREW", name: "Camera Op (Overtime)", unit: "day", costPence: 5985 },
  { category: "production", section: "PRODUCTION CREW", name: "Studio Op (Overtime)", unit: "day", costPence: 5985 },
  { category: "production", section: "PRODUCTION CREW", name: "Camera Assistant (Overtime)", unit: "day", costPence: 5237 },
  { category: "production", section: "PRODUCTION CREW", name: "Focus Puller (Overtime)", unit: "day", costPence: 5985 },
  { category: "production", section: "PRODUCTION CREW", name: "Drone Op (Overtime)", unit: "day", costPence: 29925, notes: "(with kit) check licensing" },
  { category: "production", section: "PRODUCTION CREW", name: "Sound Op (Overtime)", unit: "day", costPence: 7170 },
  { category: "production", section: "PRODUCTION CREW", name: "Sound Op (with kit) (Overtime)", unit: "day", costPence: 9663 },
  { category: "production", section: "PRODUCTION CREW", name: "Gaffer (Overtime)", unit: "day", costPence: 8229 },
  { category: "production", section: "PRODUCTION CREW", name: "Spark (Overtime)", unit: "day", costPence: 5611 },
  { category: "production", section: "PRODUCTION CREW", name: "Autocue Operator (Overtime)", unit: "day", costPence: 7481, notes: "(with kit)" },
  { category: "production", section: "PRODUCTION CREW", name: "DIT (Overtime)", unit: "day", costPence: 10474 },
  { category: "production", section: "PRODUCTION CREW", name: "Data Wrangler (Overtime)", unit: "day", costPence: 5237, notes: "just laptop" },
  { category: "production", section: "PRODUCTION CREW", name: "Vision Mixer (Overtime)", unit: "day", costPence: 6733 },
  { category: "production", section: "PRODUCTION CREW", name: "VFX Supervisor (Overtime)", unit: "day", costPence: 11970 },
  { category: "production", section: "PRODUCTION CREW", name: "Photographer (Overtime)", unit: "day", costPence: 29925 },
  { category: "production", section: "PRODUCTION CREW", name: "Photographer (Overtime)", unit: "day", costPence: 5237 },
  { category: "production", section: "PRODUCTION CREW", name: "Other", unit: "generic", costPence: 0 },
  { category: "art", section: "ART DEPARTMENT / LOCATION", name: "Art Director", unit: "day", costPence: 39900, notes: "Include prep day(s)" },
  { category: "art", section: "ART DEPARTMENT / LOCATION", name: "Art Department Assistant", unit: "day", costPence: 29925 },
  { category: "art", section: "ART DEPARTMENT / LOCATION", name: "Stylist / Prop Master", unit: "day", costPence: 39900 },
  { category: "art", section: "ART DEPARTMENT / LOCATION", name: "Props - Total Allowance", unit: "generic", costPence: 0 },
  { category: "art", section: "ART DEPARTMENT / LOCATION", name: "Hair & Make Up", unit: "day", costPence: 39900 },
  { category: "art", section: "ART DEPARTMENT / LOCATION", name: "Costume Designer", unit: "day", costPence: 44887 },
  { category: "art", section: "ART DEPARTMENT / LOCATION", name: "Wardrobe", unit: "day", costPence: 44887 },
  { category: "art", section: "ART DEPARTMENT / LOCATION", name: "Wardrobe Assistant", unit: "day", costPence: 29925 },
  { category: "art", section: "ART DEPARTMENT / LOCATION", name: "Home Economist (Prep Day)", unit: "day", costPence: 44887 },
  { category: "art", section: "ART DEPARTMENT / LOCATION", name: "Home Economist", unit: "day", costPence: 44887 },
  { category: "art", section: "ART DEPARTMENT / LOCATION", name: "Home Economist Assistant", unit: "day", costPence: 29925 },
  { category: "art", section: "ART DEPARTMENT / LOCATION", name: "Nurse/Paramedic", unit: "day", costPence: 34912 },
  { category: "art", section: "ART DEPARTMENT / LOCATION", name: "Security", unit: "day", costPence: 24937 },
  { category: "art", section: "ART DEPARTMENT / LOCATION", name: "VO Studio", unit: "day", costPence: 0 },
  { category: "art", section: "ART DEPARTMENT / LOCATION", name: "Studio Fee", unit: "day", costPence: 0 },
  { category: "art", section: "ART DEPARTMENT / LOCATION", name: "Location Fee", unit: "day", costPence: 0 },
  { category: "art", section: "ART DEPARTMENT / LOCATION", name: "Art Director (Overtime)", unit: "day", costPence: 6675 },
  { category: "art", section: "ART DEPARTMENT / LOCATION", name: "Art Department Assistant (Overtime)", unit: "day", costPence: 5025 },
  { category: "art", section: "ART DEPARTMENT / LOCATION", name: "Stylist / Prop Master (Overtime)", unit: "day", costPence: 6675 },
  { category: "art", section: "ART DEPARTMENT / LOCATION", name: "Hair & Make Up (Overtime)", unit: "day", costPence: 6675 },
  { category: "art", section: "ART DEPARTMENT / LOCATION", name: "Costume Designer (Overtime)", unit: "day", costPence: 7500 },
  { category: "art", section: "ART DEPARTMENT / LOCATION", name: "Wardrobe (Overtime)", unit: "day", costPence: 7500 },
  { category: "art", section: "ART DEPARTMENT / LOCATION", name: "Wardrobe Assistant (Overtime)", unit: "day", costPence: 5025 },
  { category: "art", section: "ART DEPARTMENT / LOCATION", name: "Home Economist (Overtime)", unit: "day", costPence: 7500 },
  { category: "art", section: "ART DEPARTMENT / LOCATION", name: "Home Economist Assistant (Overtime)", unit: "day", costPence: 5025 },
  { category: "art", section: "ART DEPARTMENT / LOCATION", name: "Nurse/Paramedic (Overtime)", unit: "day", costPence: 5850 },
  { category: "art", section: "ART DEPARTMENT / LOCATION", name: "Security (Overtime)", unit: "day", costPence: 4200 },
  { category: "art", section: "ART DEPARTMENT / LOCATION", name: "VO Studio (Overtime)", unit: "day", costPence: 500 },
  { category: "art", section: "ART DEPARTMENT / LOCATION", name: "Studio Fee (Overtime)", unit: "day", costPence: 0 },
  { category: "art", section: "ART DEPARTMENT / LOCATION", name: "Location Fee (Overtime)", unit: "day", costPence: 0 },
  { category: "art", section: "ART DEPARTMENT / LOCATION", name: "Other", unit: "generic", costPence: 0 },
  { category: "production", section: "PRODUCTION - CASTING", name: "Cast - Basic Shoot Fee", unit: "day", costPence: 39900 },
  { category: "production", section: "PRODUCTION - CASTING", name: "Cast - Wardrobe Call", unit: "day", costPence: 29925 },
  { category: "production", section: "PRODUCTION - CASTING", name: "Cast - Buyouts", unit: "day", costPence: 39900 },
  { category: "production", section: "PRODUCTION - CASTING", name: "Cast - Recalls", unit: "day", costPence: 0 },
  { category: "production", section: "PRODUCTION - CASTING", name: "Children (inc travel)", unit: "day", costPence: 39900 },
  { category: "production", section: "PRODUCTION - CASTING", name: "Children - Buyouts", unit: "day", costPence: 44888 },
  { category: "production", section: "PRODUCTION - CASTING", name: "Babies", unit: "day", costPence: 44888 },
  { category: "production", section: "PRODUCTION - CASTING", name: "Chaperones (inc travel)", unit: "day", costPence: 29925 },
  { category: "production", section: "PRODUCTION - CASTING", name: "Extras", unit: "day", costPence: 44888 },
  { category: "production", section: "PRODUCTION - CASTING", name: "Stand-ins", unit: "day", costPence: 59850 },
  { category: "production", section: "PRODUCTION - CASTING", name: "Stunt Coordinator", unit: "day", costPence: 29925 },
  { category: "production", section: "PRODUCTION - CASTING", name: "Choreographer", unit: "day", costPence: 34913 },
  { category: "production", section: "PRODUCTION - CASTING", name: "Hand Model", unit: "day", costPence: 24938 },
  { category: "production", section: "PRODUCTION - CASTING", name: "Body Double", unit: "day", costPence: 0 },
  { category: "production", section: "PRODUCTION - CASTING", name: "Animals - Casting", unit: "day", costPence: 0 },
  { category: "production", section: "PRODUCTION - CASTING", name: "Animals - Training", unit: "day", costPence: 0 },
  { category: "production", section: "PRODUCTION - CASTING", name: "Animals - Shoot", unit: "day", costPence: 0 },
  { category: "production", section: "PRODUCTION - CASTING", name: "Cast (Overtime)", unit: "day", costPence: 0 },
  { category: "production", section: "PRODUCTION - CASTING", name: "Extras (Overtime)", unit: "day", costPence: 7440 },
  { category: "production", section: "PRODUCTION - CASTING", name: "Stand-ins (Overtime)", unit: "day", costPence: 9915 },
  { category: "production", section: "PRODUCTION - CASTING", name: "Stunt Coordinator (Overtime)", unit: "day", costPence: 4965 },
  { category: "production", section: "PRODUCTION - CASTING", name: "Choreographer (Overtime)", unit: "day", costPence: 5790 },
  { category: "production", section: "PRODUCTION - CASTING", name: "Hand Model (Overtime)", unit: "day", costPence: 4140 },
  { category: "production", section: "PRODUCTION - CASTING", name: "Body Double (Overtime)", unit: "day", costPence: 0 },
  { category: "production", section: "PRODUCTION - CASTING", name: "Animals (Overtime)", unit: "day", costPence: 0 },
  { category: "production", section: "PRODUCTION - CASTING", name: "Other", unit: "generic", costPence: 0 },
  { category: "equipment", section: "EQUIPMENT", name: "Base Shooting Kit", unit: "day", costPence: 24937, notes: "FREELANCE JOBS ONLY - ADD TO DOP" },
  { category: "equipment", section: "EQUIPMENT", name: "Sony FX9 Camera Kit", unit: "day", costPence: 22444, notes: "FX9, Tripod, On-board monitor, Batteries, Cards" },
  { category: "equipment", section: "EQUIPMENT", name: "Sony FX6 Camera Kit", unit: "day", costPence: 18703, notes: "FX6, Tripod, On-board monitor, Batteries, Cards" },
  { category: "equipment", section: "EQUIPMENT", name: "Sony FX3 Camera Kit", unit: "day", costPence: 14131, notes: "FX3, Tripod, On-board monitor, Batteries, Cards" },
  { category: "equipment", section: "EQUIPMENT", name: "Gimbal Kit", unit: "day", costPence: 19950, notes: "DJI RS2, FX3, Sony 24 - 70mm,18 - 105mm Lens, Ninja V" },
  { category: "equipment", section: "EQUIPMENT", name: "Large Interview Lighting Kit", unit: "day", costPence: 24938, notes: "600D, 300D II, Amaran T2, LS60X" },
  { category: "equipment", section: "EQUIPMENT", name: "Interview Lighting Kit", unit: "day", costPence: 19950, notes: "2x 300D II, Amaran T2 LS60X" },
  { category: "equipment", section: "EQUIPMENT", name: "Prime Lens Kit", unit: "day", costPence: 27016, notes: "Sigma or Zeiss" },
  { category: "equipment", section: "EQUIPMENT", name: "Wireless Monitor Link", unit: "day", costPence: 4988 },
  { category: "equipment", section: "EQUIPMENT", name: "Zoom Link", unit: "day", costPence: 8312 },
  { category: "equipment", section: "EQUIPMENT", name: "Slider", unit: "day", costPence: 8312, notes: "Slider, 2 Monopod, Manfrotto Head" },
  { category: "equipment", section: "EQUIPMENT", name: "Green and Black Screen", unit: "day", costPence: 9975 },
  { category: "equipment", section: "EQUIPMENT", name: "GoPro Kit", unit: "day", costPence: 4988 },
  { category: "equipment", section: "EQUIPMENT", name: "EyeDirect", unit: "day", costPence: 18703 },
  { category: "equipment", section: "EQUIPMENT", name: "Monitor", unit: "day", costPence: 12469, notes: "Atomos Sumo, JVC" },
  { category: "equipment", section: "EQUIPMENT", name: "7\" Wireless Director's Monitor", unit: "day", costPence: 4156 },
  { category: "equipment", section: "EQUIPMENT", name: "Colorama Backdrop", unit: "day", costPence: 3325 },
  { category: "equipment", section: "EQUIPMENT", name: "Scrim Jim Kits", unit: "day", costPence: 3325, notes: "Manfrotto or Wescott" },
  { category: "equipment", section: "EQUIPMENT", name: "Battery Kit", unit: "day", costPence: 4988 },
  { category: "equipment", section: "EQUIPMENT", name: "Other", unit: "generic", costPence: 0 },
  { category: "equipment", section: "CAMERAS", name: "Sony FX9 Camera", unit: "day", costPence: 22443 },
  { category: "equipment", section: "CAMERAS", name: "Sony FX6 Camera", unit: "day", costPence: 16625 },
  { category: "equipment", section: "CAMERAS", name: "Sony FX3 Camera", unit: "day", costPence: 14547 },
  { category: "equipment", section: "CAMERAS", name: "Sony FX7 Camera", unit: "day", costPence: 10391 },
  { category: "equipment", section: "CAMERAS", name: "Camera (Other)", unit: "day", costPence: 0 },
  { category: "equipment", section: "CAMERAS", name: "GoPros", unit: "day", costPence: 2078 },
  { category: "equipment", section: "CAMERAS", name: "Insta 360x", unit: "day", costPence: 4156 },
  { category: "equipment", section: "LENSES", name: "Lens - Primes", unit: "day", costPence: 27431 },
  { category: "equipment", section: "LENSES", name: "Lens - Zoom Lens", unit: "day", costPence: 3325 },
  { category: "equipment", section: "LENSES", name: "Lens - Macro", unit: "day", costPence: 2909 },
  { category: "equipment", section: "LENSES", name: "Lens - Filters", unit: "day", costPence: 4156 },
  { category: "equipment", section: "LENSES", name: "Other", unit: "generic", costPence: 0 },
  { category: "equipment", section: "ACCESSORIES", name: "Tilta Nucles M Follow Focus", unit: "day", costPence: 5403 },
  { category: "equipment", section: "ACCESSORIES", name: "Tilta Mini Follow Focus", unit: "day", costPence: 1662 },
  { category: "equipment", section: "ACCESSORIES", name: "Wireless Video Transmitters", unit: "day", costPence: 5403 },
  { category: "equipment", section: "ACCESSORIES", name: "Vertical Bracket", unit: "day", costPence: 2494, notes: "Wooden Camera" },
  { category: "equipment", section: "ACCESSORIES", name: "Eyedirect", unit: "day", costPence: 10391 },
  { category: "equipment", section: "ACCESSORIES", name: "Other", unit: "generic", costPence: 0 },
  { category: "equipment", section: "GRIP", name: "Ronin DJI RS2", unit: "day", costPence: 3741 },
  { category: "equipment", section: "GRIP", name: "Slider", unit: "day", costPence: 10391 },
  { category: "equipment", section: "GRIP", name: "Satchler Tripods", unit: "day", costPence: 4156 },
  { category: "equipment", section: "GRIP", name: "C Stand", unit: "day", costPence: 831 },
  { category: "equipment", section: "GRIP", name: "Manfrotto Master Stand", unit: "day", costPence: 624 },
  { category: "equipment", section: "GRIP", name: "Manfrotto Baby Avenger Stand", unit: "day", costPence: 2078 },
  { category: "equipment", section: "GRIP", name: "Junior Boom Arm", unit: "day", costPence: 1662 },
  { category: "equipment", section: "GRIP", name: "Mini Boom Arm", unit: "day", costPence: 1662 },
  { category: "equipment", section: "GRIP", name: "Colorama Stand", unit: "day", costPence: 1662 },
  { category: "equipment", section: "GRIP", name: "K Clamps", unit: "day", costPence: 624 },
  { category: "equipment", section: "GRIP", name: "Manfrotto Magic Arm", unit: "day", costPence: 624, notes: "with Bracket" },
  { category: "equipment", section: "GRIP", name: "Matthews Scissor Clamp", unit: "day", costPence: 624, notes: "w/Cable Holder" },
  { category: "equipment", section: "GRIP", name: "Matthellini Clamp", unit: "day", costPence: 624, notes: "3” Center Jaw" },
  { category: "equipment", section: "GRIP", name: "Matthellini Clamp", unit: "day", costPence: 624, notes: "2” End Jaw" },
  { category: "equipment", section: "GRIP", name: "Sakk (Cinesaddle)", unit: "day", costPence: 1247 },
  { category: "equipment", section: "GRIP", name: "Other", unit: "generic", costPence: 0 },
  { category: "equipment", section: "MONITORING", name: "Sumo Monitor / Recorder", unit: "day", costPence: 12469 },
  { category: "equipment", section: "MONITORING", name: "JVC Monitor", unit: "day", costPence: 3741 },
  { category: "equipment", section: "MONITORING", name: "Atomos Ninja V", unit: "day", costPence: 3325 },
  { category: "equipment", section: "MONITORING", name: "SmallHD 702 OLED Monitor", unit: "day", costPence: 5403 },
  { category: "equipment", section: "MONITORING", name: "Atomos Shogun Inferno 4K", unit: "day", costPence: 5403 },
  { category: "equipment", section: "MONITORING", name: "Other", unit: "generic", costPence: 0 },
  { category: "equipment", section: "LIVESTREAM", name: "BMD Atem Television Studio Pro", unit: "day", costPence: 5403, notes: "HD" },
  { category: "equipment", section: "LIVESTREAM", name: "BMD ATEM Mini Extreme ISO", unit: "day", costPence: 5403, notes: "(HDMI)" },
  { category: "equipment", section: "LIVESTREAM", name: "Blackmagic Web Presenter HD", unit: "day", costPence: 2494 },
  { category: "equipment", section: "LIVESTREAM", name: "Tally Light System", unit: "day", costPence: 5403 },
  { category: "equipment", section: "LIVESTREAM", name: "AJA IO 4K Capture Device", unit: "day", costPence: 2494 },
  { category: "equipment", section: "LIVESTREAM", name: "Other", unit: "generic", costPence: 0 },
  { category: "equipment", section: "LIGHTING", name: "Aputure 600D", unit: "day", costPence: 10391 },
  { category: "equipment", section: "LIGHTING", name: "Aputure 300D", unit: "day", costPence: 8312 },
  { category: "equipment", section: "LIGHTING", name: "Aputure 60X", unit: "day", costPence: 2078 },
  { category: "equipment", section: "LIGHTING", name: "Amaran 2FT", unit: "day", costPence: 2078 },
  { category: "equipment", section: "LIGHTING", name: "Amaran 4FT", unit: "day", costPence: 3325 },
  { category: "equipment", section: "LIGHTING", name: "Nanline Pavotube II 6\"", unit: "day", costPence: 1247 },
  { category: "equipment", section: "LIGHTING", name: "Falconeyes 2x2", unit: "day", costPence: 1662 },
  { category: "equipment", section: "LIGHTING", name: "Falconeyes 1x0.5", unit: "day", costPence: 1246 },
  { category: "equipment", section: "LIGHTING", name: "Lighting Modifiers", unit: "day", costPence: 1246, notes: "each" },
  { category: "equipment", section: "LIGHTING", name: "Floppy 4ft", unit: "day", costPence: 1246 },
  { category: "equipment", section: "LIGHTING", name: "Floppy 6ft", unit: "day", costPence: 1246 },
  { category: "equipment", section: "LIGHTING", name: "Westcott Fast Flag", unit: "day", costPence: 2078 },
  { category: "equipment", section: "LIGHTING", name: "Infiinity White Background", unit: "day", costPence: 3325, notes: "Is this scrim jim kit or needs adding to this section" },
  { category: "equipment", section: "LIGHTING", name: "Other", unit: "generic", costPence: 0 },
  { category: "equipment", section: "SOUND", name: "Sennheiser G4", unit: "day", costPence: 2909 },
  { category: "equipment", section: "SOUND", name: "Sanken Cos 11", unit: "day", costPence: 2909 },
  { category: "equipment", section: "SOUND", name: "Rode Wireless Pro II", unit: "day", costPence: 2909 },
  { category: "equipment", section: "SOUND", name: "Sennheiser MKH416", unit: "day", costPence: 2909 },
  { category: "equipment", section: "SOUND", name: "Sennheiser MKE600", unit: "day", costPence: 2494 },
  { category: "equipment", section: "SOUND", name: "Rode NTG 1", unit: "day", costPence: 1662 },
  { category: "equipment", section: "SOUND", name: "Rode NTG 2", unit: "day", costPence: 1662 },
  { category: "equipment", section: "SOUND", name: "Rode NTG 3", unit: "day", costPence: 2078 },
  { category: "equipment", section: "SOUND", name: "Rode NTG 4", unit: "day", costPence: 2909 },
  { category: "equipment", section: "SOUND", name: "Rode NTG VideoMic", unit: "day", costPence: 1247 },
  { category: "equipment", section: "SOUND", name: "Rodecaster Pro II", unit: "day", costPence: 9975, notes: "Podcast Set (4 Mics)" },
  { category: "equipment", section: "SOUND", name: "Rodecaster Pro II", unit: "day", costPence: 3325, notes: "Mixer Only" },
  { category: "equipment", section: "SOUND", name: "Rode Boom Pole", unit: "day", costPence: 831 },
  { category: "equipment", section: "SOUND", name: "Rode Interview Go Handle", unit: "day", costPence: 831 },
  { category: "equipment", section: "SOUND", name: "Zoom H6 Kit", unit: "day", costPence: 2078 },
  { category: "equipment", section: "SOUND", name: "Other", unit: "generic", costPence: 0 },
  { category: "equipment", section: "CONSUMABLES", name: "Coloramas", unit: "day", costPence: 8312, notes: "Consumables" },
  { category: "equipment", section: "CONSUMABLES", name: "Diffusion", unit: "day", costPence: 8312, notes: "Consumables" },
  { category: "equipment", section: "CONSUMABLES", name: "Additional Consumables", unit: "day", costPence: 0, notes: "Consumables" },
  { category: "equipment", section: "CONSUMABLES", name: "Other", unit: "generic", costPence: 0 },
  { category: "equipment", section: "OTHER", name: "Walkie Talkies", unit: "day", costPence: 3325, notes: "(per pair)" },
  { category: "equipment", section: "OTHER", name: "Tripod Flight Case", unit: "day", costPence: 2078, notes: "HPRC6400W Wheeled Kit Black" },
  { category: "equipment", section: "OTHER", name: "25m 12G-SDI BNC Black Drum", unit: "day", costPence: 1246 },
  { category: "equipment", section: "OTHER", name: "Other", unit: "generic", costPence: 0 },
  { category: "travel", section: "TRAVEL & HOTELS", name: "Accommodation - Agency", unit: "day", costPence: 19950 },
  { category: "travel", section: "TRAVEL & HOTELS", name: "Accommodation - Cast", unit: "day", costPence: 19950 },
  { category: "travel", section: "TRAVEL & HOTELS", name: "Accommodation - Crew", unit: "day", costPence: 19950 },
  { category: "travel", section: "TRAVEL & HOTELS", name: "Fares", unit: "day", costPence: 0 },
  { category: "travel", section: "TRAVEL & HOTELS", name: "Mileage", unit: "mile", costPence: 41 },
  { category: "travel", section: "TRAVEL & HOTELS", name: "Taxis / Couriers", unit: "generic", costPence: 0 },
  { category: "travel", section: "TRAVEL & HOTELS", name: "Per Diems - Agency", unit: "day", costPence: 3741 },
  { category: "travel", section: "TRAVEL & HOTELS", name: "Per Diems - Client", unit: "day", costPence: 3741 },
  { category: "travel", section: "TRAVEL & HOTELS", name: "Per Diems - Production", unit: "day", costPence: 3741 },
  { category: "travel", section: "TRAVEL & HOTELS", name: "Carnet", unit: "trip", costPence: 20781 },
  { category: "travel", section: "TRAVEL & HOTELS", name: "VISAs", unit: "generic", costPence: 0 },
  { category: "travel", section: "TRAVEL & HOTELS", name: "Additional Insurance", unit: "generic", costPence: 0 },
  { category: "travel", section: "TRAVEL & HOTELS", name: "Other", unit: "generic", costPence: 0 },
  { category: "post", section: "POST - PRODUCTION", name: "Offline Editor", unit: "day", costPence: 41562 },
  { category: "post", section: "POST - PRODUCTION", name: "Offline Editor - Amends", unit: "day", costPence: 41562 },
  { category: "post", section: "POST - PRODUCTION", name: "Online Editor - Versioning", unit: "day", costPence: 41562 },
  { category: "post", section: "POST - PRODUCTION", name: "Ingest", unit: "day", costPence: 29925, notes: "Use for multicamera jobs" },
  { category: "post", section: "POST - PRODUCTION", name: "Edit Assistant", unit: "day", costPence: 34912 },
  { category: "post", section: "POST - PRODUCTION", name: "Motion GFX Artist", unit: "day", costPence: 59850 },
  { category: "post", section: "POST - PRODUCTION", name: "Sound Design", unit: "day", costPence: 39900 },
  { category: "post", section: "POST - PRODUCTION", name: "Sound Mix / Mastering", unit: "day", costPence: 44887 },
  { category: "post", section: "POST - PRODUCTION", name: "2D Animation - Graphics", unit: "day", costPence: 49875 },
  { category: "post", section: "POST - PRODUCTION", name: "3D Animation - Graphics", unit: "day", costPence: 49875 },
  { category: "post", section: "POST - PRODUCTION", name: "2D Nuke/Flame", unit: "day", costPence: 78969 },
  { category: "post", section: "POST - PRODUCTION", name: "Colourist", unit: "day", costPence: 62344 },
  { category: "post", section: "POST - PRODUCTION", name: "Edit Hire", unit: "generic", costPence: 29925 },
  { category: "post", section: "POST - PRODUCTION", name: "Library Music", unit: "track", costPence: 1662 },
  { category: "post", section: "POST - PRODUCTION", name: "Stock Images", unit: "generic", costPence: 0 },
  { category: "post", section: "POST - PRODUCTION", name: "Stock Footage Library", unit: "minute", costPence: 6234, notes: "Artgrid & Envato Library Covered" },
  { category: "post", section: "POST - PRODUCTION", name: "Licensing Footage", unit: "generic", costPence: 0 },
  { category: "post", section: "POST - PRODUCTION", name: "Hard Drives", unit: "item", costPence: 12468, notes: "1TB" },
  { category: "post", section: "POST - PRODUCTION", name: "Archiving", unit: "generic", costPence: 12468, notes: "Include on all jobs" },
  { category: "post", section: "POST - PRODUCTION", name: "Transcription", unit: "minute", costPence: 166 },
  { category: "post", section: "POST - PRODUCTION", name: "Couriers", unit: "generic", costPence: 0 },
  { category: "post", section: "POST - PRODUCTION", name: "Offline Editor (Overtime)", unit: "day", costPence: 6900 },
  { category: "post", section: "POST - PRODUCTION", name: "Edit Assistant (Overtime)", unit: "day", costPence: 5850 },
  { category: "post", section: "POST - PRODUCTION", name: "Motion GFX Artist (Overtime)", unit: "day", costPence: 9975 },
  { category: "post", section: "POST - PRODUCTION", name: "Sound Design (Overtime)", unit: "day", costPence: 6675 },
  { category: "post", section: "POST - PRODUCTION", name: "Sound Mix / Mastering (Overtime)", unit: "day", costPence: 7500 },
  { category: "post", section: "POST - PRODUCTION", name: "2D Animation GFX (Overtime)", unit: "day", costPence: 8325 },
  { category: "post", section: "POST - PRODUCTION", name: "3D Animation GFX(Overtime)", unit: "day", costPence: 8325 },
  { category: "post", section: "POST - PRODUCTION", name: "2D Nuke/Flame (Overtime)", unit: "day", costPence: 13125 },
  { category: "post", section: "POST - PRODUCTION", name: "Colourist (Overtime)", unit: "day", costPence: 10350 },
  { category: "post", section: "POST - PRODUCTION", name: "Edit Hire (Overtime)", unit: "generic", costPence: 5025 },
  { category: "post", section: "POST - PRODUCTION", name: "Other", unit: "generic", costPence: 0 },
];
